name: Build and Release LaTeX Document

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3
    
    # Experimental BEGIN
    # Set up TeX Live environment and install makeindex
    - name: Set up TeX Live and install makeindex
      run: |
        sudo apt-get update
        sudo apt-get install texlive-binaries
    # Experimental END
    
    # Set up TeX Live environment
    - name: Set up TeX Live
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex  # Update this if your main file has a different name
        latexmk_shell_escape: true  # Enable shell escape if your document uses external tools like `minted`
        texlive_version: 2024
        extra_system_packages: |
          texlive-latex-extra
          texlive-fonts-recommended
          texlive-science
          makeindex


    # # Experimental Begin //
    #  # List files for debugging
    # - name: List files for debugging
    #   run: ls -alh

    # # Run makeindex to process the index
    # # - name: Run makeindex
    # #   run: makeindex main
    # #   working-directory: ./  # Ensure the correct directory
    # - name: Run makeindex with debugging
    #   run: |
    #     makeindex main.idx -o main.ind
    #     cat main.ind  # Output the content of the index file


    # # Recompile to include the index
    # - name: Final LaTeX Compilation
    #   run: latexmk -pdf -shell-escape main.tex
    # # Experimental End //
    
    # Rename the PDF file
    - name: Rename PDF
      run: mv main.pdf Modern_Algebra_with_Friends_Textbook.pdf
      
    # Upload the compiled PDF as a release asset
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.BUILD_PDF_SECRET }}
      with:
        tag_name: v1.${{ github.run_number }}  # Auto-generated tag for each run
        release_name: "Compiled Modern Algebra With Friends PDF v1.${{ github.run_number }}"
        body: "This release includes the latest version of the compiled LaTeX document."
        draft: false
        prerelease: false

    - name: Upload MAWF PDF to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.BUILD_PDF_SECRET }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: Modern_Algebra_with_Friends_Textbook.pdf
        asset_name: Modern_Algebra_with_Friends_Textbook.pdf
        asset_content_type: application/pdf
