name: Build and Release LaTeX Document

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Uncomment this block and comment the block below if you want to use the standard pdflatex build recipe
    # # Set up TeX Live environment
    # - name: Set up TeX Live
    #   uses: xu-cheng/latex-action@v3
    #   with:
    #     root_file: main.tex  # Update this if your main file has a different name
    #     latexmk_shell_escape: true  # Enable shell escape if your document uses external tools like `minted`
    #     texlive_version: 2024

    # I use a custom recipe 
    # (pdflatex once then makeindex pointing to my styleInd.ist then biber, then pdflatex 2 more times)
    - name: Build MAWF Using LeGrands Recipe 
      uses: xu-cheng/texlive-action@v2
      with:
        scheme: full
        run: |
          pdflatex  -file-line-error -halt-on-error -interaction=nonstopmode -shell-escape -recorder  "main.tex"
          makeindex main.idx -s StyleInd.ist
          biber main
          pdflatex  -file-line-error -halt-on-error -interaction=nonstopmode -shell-escape -recorder  "main.tex"
          pdflatex  -file-line-error -halt-on-error -interaction=nonstopmode -shell-escape -recorder  "main.tex"
          
    # Rename the PDF file
    - name: Rename PDF
      run: mv main.pdf "Modern_Algebra_with_Friends_Textbook_v1.${{ github.run_number }}.pdf"
      
    # Upload the compiled PDF as a release asset
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.BUILD_PDF_SECRET }}
      with:
        tag_name: v1.${{ github.run_number }}  # Auto-generated tag for each run
        release_name: "Compiled Modern Algebra With Friends PDF v1.${{ github.run_number }}"
        body: "This release includes the latest version of the compiled LaTeX document."
        draft: false
        prerelease: false

    - name: Upload MAWF PDF to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.BUILD_PDF_SECRET }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: "Modern_Algebra_with_Friends_Textbook_v1.${{ github.run_number }}.pdf"
        asset_name: "Modern_Algebra_with_Friends_Textbook_v1.${{ github.run_number }}.pdf"
        asset_content_type: application/pdf
